### ISSUE TITLE
R4i-SDHC RTS not working

### ISSUE THREAD

**Issue by kasianvh** [kitling/ntrboot_flasher#3]
will the R4i-SDHC ever work with ntrboot?

**Comment by CookieXD** [comment]
and what's with the Ace3ds Plus?

**Comment by N00byKing** [comment]
I don't think Ace3DS+ will ever work because it is a CTR Card (it identifies as a 3DS, not NDS or DSi Card)
However I am no expert, you should probably ask around on the Nintendo Discord Channel or something (https://discord.gg/MWxPgEp)

**Comment by chronoss09** [comment]
And nothing for R4 Dual Core RTS Lite ?

**Comment by kitling** [comment]
So... is everyone here just asking when their cart will be supported? I'm afraid that I can't give an answer on that, and quite frankly, this is not what Github issues are for.

The only cards supported right now are in the readme. There's some leeway on the R4i (Gold?) 3DS (RTS?) because, frankly, I'm not quite sure which cards fall under it's category.

If you want to help with this, please find an updater that works for your flashcart (*.nds format) and open an issue on [flashcart_core](https://github.com/kitling/flashcart_core) with a link to an updater. If you can do some reverse engineering/have IDA, it would be much appreciated if you could find the cartridge commands (Read, Write, a means of identifying the cart, flashbusy, anything needed for setup) and post them in that issue.

**Comment by TheSitX** [comment]
Sky3ds plus , will be added?

**Comment by hedgeberg** [comment]
The sky3ds cannot behave as an ntr cart, so no. Please stop asking on this repo and read the readme.
