### ISSUE TITLE
plz i have r4 card sdhc dual-core 2016 and i waiting 1 month ntrboot for this card in my city have just sdhc dual core 2016 no auther card help plz or release date if you can thx

### ISSUE THREAD

**Issue by hack0123** [kitling/ntrboot_flasher#51]

**Comment by kitling** [comment]
1. This is not the place for you to ask if your card can be supported. I'm pretty sure the issue template tells you where to go.
2. You provided no useful information about this card. Thankfully, other people have already done so.
3. There is no ETA. People are busy, and I'm currently trying to fix some things that bugged me since before release.
4. The description field is there for a reason?
